In [1]:
import pandas as pd
import datetime

today = datetime.datetime.now()
Timestamp1 = pd.date_range(start=today,
                          end='2022-05-19',
                          freq='D')
print('1-1.')
print(Timestamp1)

1-1.
DatetimeIndex(['2022-04-28 09:09:46.184406', '2022-04-29 09:09:46.184406',
               '2022-04-30 09:09:46.184406', '2022-05-01 09:09:46.184406',
               '2022-05-02 09:09:46.184406', '2022-05-03 09:09:46.184406',
               '2022-05-04 09:09:46.184406', '2022-05-05 09:09:46.184406',
               '2022-05-06 09:09:46.184406', '2022-05-07 09:09:46.184406',
               '2022-05-08 09:09:46.184406', '2022-05-09 09:09:46.184406',
               '2022-05-10 09:09:46.184406', '2022-05-11 09:09:46.184406',
               '2022-05-12 09:09:46.184406', '2022-05-13 09:09:46.184406',
               '2022-05-14 09:09:46.184406', '2022-05-15 09:09:46.184406',
               '2022-05-16 09:09:46.184406', '2022-05-17 09:09:46.184406',
               '2022-05-18 09:09:46.184406'],
              dtype='datetime64[ns]', freq='D')

In [39]:
Timestamp2 = pd.date_range(start=today,
                          periods=63,
                          freq='D')

print('1-2.')
print(Timestamp2)

1-2.
DatetimeIndex(['2022-04-27 17:43:12.647759', '2022-04-28 17:43:12.647759',
               '2022-04-29 17:43:12.647759', '2022-04-30 17:43:12.647759',
               '2022-05-01 17:43:12.647759', '2022-05-02 17:43:12.647759',
               '2022-05-03 17:43:12.647759', '2022-05-04 17:43:12.647759',
               '2022-05-05 17:43:12.647759', '2022-05-06 17:43:12.647759',
               '2022-05-07 17:43:12.647759', '2022-05-08 17:43:12.647759',
               '2022-05-09 17:43:12.647759', '2022-05-10 17:43:12.647759',
               '2022-05-11 17:43:12.647759', '2022-05-12 17:43:12.647759',
               '2022-05-13 17:43:12.647759', '2022-05-14 17:43:12.647759',
               '2022-05-15 17:43:12.647759', '2022-05-16 17:43:12.647759',
               '2022-05-17 17:43:12.647759', '2022-05-18 17:43:12.647759',
               '2022-05-19 17:43:12.647759', '2022-05-20 17:43:12.647759',
               '2022-05-21 17:43:12.647759', '2022-05-22 17:43:12.647759',
               '2022-05-23 17:43:12.647759', '2022-05-24 17:43:12.647759',
               '2022-05-25 17:43:12.647759', '2022-05-26 17:43:12.647759',
               '2022-05-27 17:43:12.647759', '2022-05-28 17:43:12.647759',
               '2022-05-29 17:43:12.647759', '2022-05-30 17:43:12.647759',
               '2022-05-31 17:43:12.647759', '2022-06-01 17:43:12.647759',
               '2022-06-02 17:43:12.647759', '2022-06-03 17:43:12.647759',
               '2022-06-04 17:43:12.647759', '2022-06-05 17:43:12.647759',
               '2022-06-06 17:43:12.647759', '2022-06-07 17:43:12.647759',
               '2022-06-08 17:43:12.647759', '2022-06-09 17:43:12.647759',
               '2022-06-10 17:43:12.647759', '2022-06-11 17:43:12.647759',
               '2022-06-12 17:43:12.647759', '2022-06-13 17:43:12.647759',
               '2022-06-14 17:43:12.647759', '2022-06-15 17:43:12.647759',
               '2022-06-16 17:43:12.647759', '2022-06-17 17:43:12.647759',
               '2022-06-18 17:43:12.647759', '2022-06-19 17:43:12.647759',
               '2022-06-20 17:43:12.647759', '2022-06-21 17:43:12.647759',
               '2022-06-22 17:43:12.647759', '2022-06-23 17:43:12.647759',
               '2022-06-24 17:43:12.647759', '2022-06-25 17:43:12.647759',
               '2022-06-26 17:43:12.647759', '2022-06-27 17:43:12.647759',
               '2022-06-28 17:43:12.647759'],
              dtype='datetime64[ns]', freq='D')

In [40]:
Timestamp3 = pd.date_range(start='2022-01-01',
                          periods=12,
                          freq='M')

print('1-3.')
print(Timestamp3)

1-3.
DatetimeIndex(['2022-01-31', '2022-02-28', '2022-03-31', '2022-04-30',
               '2022-05-31', '2022-06-30', '2022-07-31', '2022-08-31',
               '2022-09-30', '2022-10-31', '2022-11-30', '2022-12-31'],
              dtype='datetime64[ns]', freq='M')

In [41]:
Timestamp4 = pd.date_range(start='2022-01-01',
                          periods=12,
                          freq='MS')

print('1-4.')
print(Timestamp4)

1-4.
DatetimeIndex(['2022-01-01', '2022-02-01', '2022-03-01', '2022-04-01',
               '2022-05-01', '2022-06-01', '2022-07-01', '2022-08-01',
               '2022-09-01', '2022-10-01', '2022-11-01', '2022-12-01'],
              dtype='datetime64[ns]', freq='MS')

In [42]:
Timestamp5 = pd.date_range(start='2022-04-27',
                          end='2022-05-05',
                          freq='H')

print('1-5.')
print(Timestamp5)

1-5.
DatetimeIndex(['2022-04-27 00:00:00', '2022-04-27 01:00:00',
               '2022-04-27 02:00:00', '2022-04-27 03:00:00',
               '2022-04-27 04:00:00', '2022-04-27 05:00:00',
               '2022-04-27 06:00:00', '2022-04-27 07:00:00',
               '2022-04-27 08:00:00', '2022-04-27 09:00:00',
               ...
               '2022-05-04 15:00:00', '2022-05-04 16:00:00',
               '2022-05-04 17:00:00', '2022-05-04 18:00:00',
               '2022-05-04 19:00:00', '2022-05-04 20:00:00',
               '2022-05-04 21:00:00', '2022-05-04 22:00:00',
               '2022-05-04 23:00:00', '2022-05-05 00:00:00'],
              dtype='datetime64[ns]', length=193, freq='H')

In [2]:
Timestamp6 = pd.date_range(start='2022-04-27',
                          end='2022-05-05 18:00',
                          freq='3H')

print('1-6.')
print(Timestamp6)

1-6.
DatetimeIndex(['2022-04-27 00:00:00', '2022-04-27 03:00:00',
               '2022-04-27 06:00:00', '2022-04-27 09:00:00',
               '2022-04-27 12:00:00', '2022-04-27 15:00:00',
               '2022-04-27 18:00:00', '2022-04-27 21:00:00',
               '2022-04-28 00:00:00', '2022-04-28 03:00:00',
               '2022-04-28 06:00:00', '2022-04-28 09:00:00',
               '2022-04-28 12:00:00', '2022-04-28 15:00:00',
               '2022-04-28 18:00:00', '2022-04-28 21:00:00',
               '2022-04-29 00:00:00', '2022-04-29 03:00:00',
               '2022-04-29 06:00:00', '2022-04-29 09:00:00',
               '2022-04-29 12:00:00', '2022-04-29 15:00:00',
               '2022-04-29 18:00:00', '2022-04-29 21:00:00',
               '2022-04-30 00:00:00', '2022-04-30 03:00:00',
               '2022-04-30 06:00:00', '2022-04-30 09:00:00',
               '2022-04-30 12:00:00', '2022-04-30 15:00:00',
               '2022-04-30 18:00:00', '2022-04-30 21:00:00',
               '2022-05-01 00:00:00', '2022-05-01 03:00:00',
               '2022-05-01 06:00:00', '2022-05-01 09:00:00',
               '2022-05-01 12:00:00', '2022-05-01 15:00:00',
               '2022-05-01 18:00:00', '2022-05-01 21:00:00',
               '2022-05-02 00:00:00', '2022-05-02 03:00:00',
               '2022-05-02 06:00:00', '2022-05-02 09:00:00',
               '2022-05-02 12:00:00', '2022-05-02 15:00:00',
               '2022-05-02 18:00:00', '2022-05-02 21:00:00',
               '2022-05-03 00:00:00', '2022-05-03 03:00:00',
               '2022-05-03 06:00:00', '2022-05-03 09:00:00',
               '2022-05-03 12:00:00', '2022-05-03 15:00:00',
               '2022-05-03 18:00:00', '2022-05-03 21:00:00',
               '2022-05-04 00:00:00', '2022-05-04 03:00:00',
               '2022-05-04 06:00:00', '2022-05-04 09:00:00',
               '2022-05-04 12:00:00', '2022-05-04 15:00:00',
               '2022-05-04 18:00:00', '2022-05-04 21:00:00',
               '2022-05-05 00:00:00', '2022-05-05 03:00:00',
               '2022-05-05 06:00:00', '2022-05-05 09:00:00',
               '2022-05-05 12:00:00', '2022-05-05 15:00:00',
               '2022-05-05 18:00:00'],
              dtype='datetime64[ns]', freq='3H')

In [44]:
Timestamp7 = pd.date_range(start='2022-01-01',
                          periods=8,
                          freq='2M')

print('1-7.')
print(Timestamp7)

1-7.
DatetimeIndex(['2022-01-31', '2022-03-31', '2022-05-31', '2022-07-31',
               '2022-09-30', '2022-11-30', '2023-01-31', '2023-03-31'],
              dtype='datetime64[ns]', freq='2M')

In [45]:
df = pd.read_csv('./data/product_click.log',
                 header=None,
                 sep=" ",
                 dtype="object")
df.columns = ['oldclicktime','clickpid']
df['newclicktime'] = pd.to_datetime(df['oldclicktime'])
print("2-1.")
print(df.info())
print(df.head(5))

2-1.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 746 entries, 0 to 745
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   oldclicktime  746 non-null    object
 1   clickpid      746 non-null    object
 2   newclicktime  746 non-null    datetime64[ns]
dtypes: datetime64[ns](1), object(2)
memory usage: 17.6+ KB
None
   oldclicktime clickpid        newclicktime
0  201612120944     p001 2016-12-12 09:44:00
1  201612120944     p003 2016-12-12 09:44:00
2  201612120944     p003 2016-12-12 09:44:00
3  201612120945     p008 2016-12-12 09:45:00
4  201612121052     p008 2016-12-12 10:52:00

In [46]:
df_time = df
df_time['year'] = df_time['newclicktime'].dt.year
df_time['month'] = df_time['newclicktime'].dt.month
df_time['day'] = df_time['newclicktime'].dt.day
df_time['hour'] = df_time['newclicktime'].dt.hour
df_time['minute'] = df_time['newclicktime'].dt.minute
print("2-2.")
print(df_time.info())
print(df_time.head())

2-2.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 746 entries, 0 to 745
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   oldclicktime  746 non-null    object
 1   clickpid      746 non-null    object
 2   newclicktime  746 non-null    datetime64[ns]
 3   year          746 non-null    int64
 4   month         746 non-null    int64
 5   day           746 non-null    int64
 6   hour          746 non-null    int64
 7   minute        746 non-null    int64
dtypes: datetime64[ns](1), int64(5), object(2)
memory usage: 46.8+ KB
None
   oldclicktime clickpid        newclicktime  year  month  day  hour  minute
0  201612120944     p001 2016-12-12 09:44:00  2016     12   12     9      44
1  201612120944     p003 2016-12-12 09:44:00  2016     12   12     9      44
2  201612120944     p003 2016-12-12 09:44:00  2016     12   12     9      44
3  201612120945     p008 2016-12-12 09:45:00  2016     12   12     9      45
4  201612121052     p008 2016-12-12 10:52:00  2016     12   12    10      52

In [50]:
df2 = pd.read_csv('./data/cctv_seoul.csv')

def ratio_two_obj(a, b):    # 두 객체의 합
    return a / b * 100

df2['CCTV비율'] = df2.apply(lambda x: ratio_two_obj(x['CCTV수'], x['인구수']), axis=1)   
df2['노인비율'] = df2.apply(lambda x: ratio_two_obj(x['고령자'], x['인구수']), axis=1)   

print('3')
print(df2.head())

3
    구별  CCTV수       인구수       한국인      외국인      고령자    CCTV비율       노인비율
0  강남구   2780  570500.0  565550.0   4950.0  63167.0  0.487292  11.072217
1  강동구    773  453233.0  449019.0   4214.0  54622.0  0.170552  12.051638
2  강북구    748  330192.0  326686.0   3506.0  54813.0  0.226535  16.600342
3  강서구    884  603772.0  597248.0   6524.0  72548.0  0.146413  12.015794
4  관악구   1496  525515.0  507203.0  18312.0  68082.0  0.284673  12.955291